markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Life In a Terminal
url: 
subscribe:
exclude: [ README README.md, newpost.rb ]
domain:
author: nuomi
email: newchar@gmail.com
auto: false
twitterID: nuomi
googleAnalyticsID: 
disqusShortname: 
